- pkg:maven/eu.hansolo.fx/charts@11.1
- pkg:maven/eu.hansolo.fx/charts@11.1?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.2
- pkg:maven/eu.hansolo.fx/charts@11.2?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.3
- pkg:maven/eu.hansolo.fx/charts@11.3?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.4
- pkg:maven/eu.hansolo.fx/charts@11.4?classifier=sources
