- pkg:maven/eu.hansolo.fx/charts@11.1
- pkg:maven/eu.hansolo.fx/charts@11.1?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.2
- pkg:maven/eu.hansolo.fx/charts@11.2?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.3
- pkg:maven/eu.hansolo.fx/charts@11.3?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.4
- pkg:maven/eu.hansolo.fx/charts@11.4?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.5
- pkg:maven/eu.hansolo.fx/charts@11.5?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.6
- pkg:maven/eu.hansolo.fx/charts@11.6?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.7
- pkg:maven/eu.hansolo.fx/charts@11.7?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.0?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.2?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.3?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.4?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.5?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.6?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.7?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.8?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.9?classifier=sources
