- pkg:maven/eu.hansolo.fx/charts@11.1
- pkg:maven/eu.hansolo.fx/charts@11.10?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.11?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.12?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.1?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.2
- pkg:maven/eu.hansolo.fx/charts@11.2?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.3
- pkg:maven/eu.hansolo.fx/charts@11.3?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.4
- pkg:maven/eu.hansolo.fx/charts@11.4?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.5
- pkg:maven/eu.hansolo.fx/charts@11.5?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.6
- pkg:maven/eu.hansolo.fx/charts@11.6?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.7
- pkg:maven/eu.hansolo.fx/charts@11.7?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.8?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@11.9?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.0?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.10?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.11?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.12?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.13?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.14?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.15?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.16?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.2?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.3?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.4?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.5?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.6?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.7?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.8?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@16.0.9?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.0?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.10?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.11?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.14?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.15?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.17?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.19?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.1?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.21?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.22?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.23?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.2?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.3?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.4?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.5?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.6?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.7?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.8?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.0.9?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.0?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.11?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.12?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.13?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.14?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.15?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.17?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.19?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.1?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.21?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.23?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.25?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.27?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.2?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.31?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.35?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.37?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.39?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.3?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.4?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.5?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.6?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.7?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.8?classifier=sources
- pkg:maven/eu.hansolo.fx/charts@17.1.9?classifier=sources
