- pkg:maven/dev.chopsticks/chopsticks-prometheus_2.13@3.10.0
- pkg:maven/dev.chopsticks/chopsticks-prometheus_2.13@3.10.0?classifier=sources
- pkg:maven/dev.chopsticks/chopsticks-prometheus_2.13@3.11.0
- pkg:maven/dev.chopsticks/chopsticks-prometheus_2.13@3.11.0?classifier=sources
- pkg:maven/dev.chopsticks/chopsticks-prometheus_2.13@3.12.0
- pkg:maven/dev.chopsticks/chopsticks-prometheus_2.13@3.12.0?classifier=sources
- pkg:maven/dev.chopsticks/chopsticks-prometheus_2.13@3.9.2
- pkg:maven/dev.chopsticks/chopsticks-prometheus_2.13@3.9.2?classifier=sources
- pkg:maven/dev.chopsticks/chopsticks-prometheus_2.13@4.0.0
- pkg:maven/dev.chopsticks/chopsticks-prometheus_2.13@4.0.0?classifier=sources
