- pkg:maven/no.difi.move-common/config@1.1.11
- pkg:maven/no.difi.move-common/config@1.1.11?classifier=sources
- pkg:maven/no.difi.move-common/config@1.1.8
- pkg:maven/no.difi.move-common/config@1.1.8?classifier=sources
