- pkg:maven/com.github.wasiqb.coteafs/configs@0.0.1
- pkg:maven/com.github.wasiqb.coteafs/configs@0.0.1?classifier=sources
- pkg:maven/com.github.wasiqb.coteafs/configs@1.0.0
- pkg:maven/com.github.wasiqb.coteafs/configs@1.0.0?classifier=sources
- pkg:maven/com.github.wasiqb.coteafs/configs@1.1.0
- pkg:maven/com.github.wasiqb.coteafs/configs@1.1.0?classifier=sources
- pkg:maven/com.github.wasiqb.coteafs/configs@1.2.0
- pkg:maven/com.github.wasiqb.coteafs/configs@1.2.0?classifier=sources
- pkg:maven/com.github.wasiqb.coteafs/configs@1.3.0
- pkg:maven/com.github.wasiqb.coteafs/configs@1.3.0?classifier=sources
- pkg:maven/com.github.wasiqb.coteafs/configs@1.4.0
- pkg:maven/com.github.wasiqb.coteafs/configs@1.4.0?classifier=sources
- pkg:maven/com.github.wasiqb.coteafs/configs@1.5.0
- pkg:maven/com.github.wasiqb.coteafs/configs@1.5.0?classifier=sources
- pkg:maven/com.github.wasiqb.coteafs/configs@1.6.0
- pkg:maven/com.github.wasiqb.coteafs/configs@1.6.0?classifier=sources
- pkg:maven/com.github.wasiqb.coteafs/configs@1.7.0
- pkg:maven/com.github.wasiqb.coteafs/configs@1.7.0?classifier=sources
- pkg:maven/com.github.wasiqb.coteafs/configs@1.8.0
- pkg:maven/com.github.wasiqb.coteafs/configs@1.8.0?classifier=sources
- pkg:maven/com.github.wasiqb.coteafs/configs@2.0.0
- pkg:maven/com.github.wasiqb.coteafs/configs@2.0.0?classifier=sources
- pkg:maven/com.github.wasiqb.coteafs/configs@2.1.0
- pkg:maven/com.github.wasiqb.coteafs/configs@2.1.0?classifier=sources
- pkg:maven/com.github.wasiqb.coteafs/configs@2.1.1
- pkg:maven/com.github.wasiqb.coteafs/configs@2.1.1?classifier=sources
- pkg:maven/com.github.wasiqb.coteafs/configs@2.1.2
- pkg:maven/com.github.wasiqb.coteafs/configs@2.1.2?classifier=sources
- pkg:maven/com.github.wasiqb.coteafs/configs@2.1.3
- pkg:maven/com.github.wasiqb.coteafs/configs@2.1.3?classifier=sources
- pkg:maven/com.github.wasiqb.coteafs/configs@2.1.4
- pkg:maven/com.github.wasiqb.coteafs/configs@2.1.4?classifier=sources
- pkg:maven/com.github.wasiqb.coteafs/configs@2.2.0
- pkg:maven/com.github.wasiqb.coteafs/configs@2.2.0?classifier=sources
