- pkg:maven/com.alibaba.fluss/fluss-metrics-prometheus@0.5.0
- pkg:maven/com.alibaba.fluss/fluss-metrics-prometheus@0.5.0?classifier=sources
- pkg:maven/com.alibaba.fluss/fluss-metrics-prometheus@0.6.0
- pkg:maven/com.alibaba.fluss/fluss-metrics-prometheus@0.6.0?classifier=sources
