- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@1.0.1
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@1.0.1?classifier=sources
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@1.0.2
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@1.0.2?classifier=sources
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@1.0.3
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@1.0.3?classifier=sources
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@1.0.5
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@1.0.5?classifier=sources
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@2.0.0
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@2.0.0?classifier=sources
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@2.0.1
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@2.0.1?classifier=sources
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@2.2.0
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@2.2.0?classifier=sources
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@2.3.0
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@2.3.0?classifier=sources
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@2.3.1
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@2.3.1?classifier=sources
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@2.4.0
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@2.4.0?classifier=sources
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@2.5.0
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@2.5.0?classifier=sources
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@2.5.1
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@2.5.1?classifier=sources
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@3.0.0
- pkg:maven/com.dkanejs.maven.plugins/docker-compose-maven-plugin@3.0.0?classifier=sources
