- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-starter@0.0.1
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-starter@0.0.1?classifier=sources
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-starter@0.15.0
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-starter@0.15.0?classifier=sources
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-starter@0.17.9
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-starter@0.17.9?classifier=sources
